### ISSUE TITLE
Positive look-ahead fails. Example: (?=[0-9])\S

### ISSUE THREAD

**Issue by pkrumins** [fent/randexp.js#33] opened 2017-09-05 01:31 UTC
I've discovered that randex.js fails to respect a positive look-ahead regular expression. Here's a simple failing regex:

`(?=[0-9])\S`

It should only generate a single digit but it fails to do so. It works just as if I had simple `\S`.

**Comment by fent** [comment] 2017-09-05 01:45
Dupe of #18

**Closed by fent** 2017-09-05 01:45 UTC
