### ISSUE TITLE
Bug found

### ISSUE THREAD

**Issue by ruiruiruiruirain** [fent/randexp.js#69] opened 2019-07-06 22:04 UTC
A little bug was found when I defined my reg as '/(?!.*[0-9])^\w{6}/' and it turns 'JeXs3u' back. The number can't be here. I tried a lot of times and it's always number here. 
Thanks
<img width="760" alt="屏幕快照 2019-07-07 05 57 42" src="https://user-images.githubusercontent.com/38995498/60761518-9c4a1380-a07c-11e9-8d91-945af483b4b0.png">

**Comment by fent** [comment] 2019-07-06 22:31
The positional (`^`) is ignored by randexp, otherwise, this regex wouldn't match anything

Negative lookbacks are not currently working, dupe of https://github.com/fent/randexp.js/issues/18

**Closed by fent** 2019-07-06 22:31 UTC
