### ISSUE TITLE
Negative lookup seems to not be working

### ISSUE THREAD

**Issue by cgutierrezpa** [fent/randexp.js#37] opened 2017-10-23 08:32 UTC
So I want to generate a random expression that does not contain a certain combination of characters. For example, let's imagine that I want to generate 2-character words with the letters 'a' and 'b' such that I can generate:

'aa'
'ab'
'ba'
'bb'

Then I want the generator to avoid generating one of those words, for instance 'aa', for which I created the following Regular Expression:

`/((?!aa)[a-b]){2}/`

However, a `randexp` based on this Regular Expression will be generating all of the words listed above, including 'aa' which is supposed to be skipped. 

![image](https://user-images.githubusercontent.com/20757456/31879321-5d0a0b14-b7dd-11e7-8983-e402872b3fb8.png)

Isn't this considered by the algorithm? Is there something wrong with my Regular Expression? Or is there a bug in the algorithm?

Thanks in advance.

**Comment by fent** [comment] 2017-10-25 03:24
Currently, negative lookaheads are ignored.

Dupe of #18

**Closed by fent** 2017-10-25 03:24 UTC
