### ISSUE TITLE
RandExp generates strings that do not match 

### ISSUE THREAD

**Issue by sfenu** [fent/randexp.js#31] opened 2017-06-08 07:30 UTC
Hi,

thank you very match for this useful tool.
Anyway, I would like to report that the following regex sometimes generates strings that do not match:

/^(?=.*?[a-z])(?=.*?[A-Z])(?=.*?[0-9]).{8,72}$/

You can find in attachment a test file for mocha which easily reproduces the issue.

[test-randexp.zip](https://github.com/fent/randexp.js/files/1060213/test-randexp.zip)

Best regards
Stefano

**Comment by fent** [comment] 2017-06-08 12:27
Duplicate of #18

**Closed by fent** 2017-06-08 12:27 UTC
